-- ============================================================================
-- Disease2Target — Knowledge Graph tables (phase 1)
-- Run as DISEASE2TARGET_OWNER, after the content tables already exist.
-- Compatible with Oracle 19c+ (no Property Graph / PGQ dependency).
--
-- A materialised property graph PROJECTED from the EVIDENCE + RANKING_SCORES of a
-- snapshot. Genes, diseases, drugs, trials, pathways, tissues, papers and variants
-- become NODES; the relationships buried inside EVIDENCE.value_json become EDGES.
-- Built idempotently per snapshot by `scripts/d2t.ts kg <snapshotId>` — a rebuild
-- deletes the snapshot's rows first, so it never duplicates.
--
-- Two tables:
--   kg_nodes  — one row per entity, in one snapshot
--   kg_edges  — one row per relationship, in one snapshot
-- ============================================================================


-- ── 1. KG_NODES ─────────────────────────────────────────────────────────────
-- node_key is the stable, unique-within-snapshot identifier the edges join on,
-- e.g. 'gene:KRAS', 'disease:MONDO_0006047', 'drug:sotorasib',
--      'trial:NCT03600883', 'pathway:egfr-signaling', 'tissue:pancreas',
--      'paper:PMID12345678', 'variant:KRAS:G12D'.
CREATE TABLE kg_nodes (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id  NUMBER        NOT NULL,   -- which projected graph this belongs to
  disease_id   VARCHAR2(100) NOT NULL,
  node_key     VARCHAR2(200) NOT NULL,   -- 'gene:KRAS' etc. (type prefix + id)
  node_type    VARCHAR2(30)  NOT NULL,   -- gene | disease | drug | trial | pathway | tissue | paper | variant
  label        VARCHAR2(400),            -- human-readable display name
  degree       NUMBER DEFAULT 0,         -- edge count (precomputed for god-node queries)
  props_json   CLOB,                     -- structured payload (scores, ids, urls…)
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_kgn_json CHECK (props_json IS JSON),
  CONSTRAINT uq_kgn_key UNIQUE (snapshot_id, node_key),
  CONSTRAINT fk_kgn_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES target_ranking_snapshots (id) ON DELETE CASCADE
);
CREATE INDEX idx_kgn_snapshot ON kg_nodes (snapshot_id);
CREATE INDEX idx_kgn_type     ON kg_nodes (snapshot_id, node_type);


-- ── 2. KG_EDGES ─────────────────────────────────────────────────────────────
-- One row per relationship. src_key / dst_key reference kg_nodes.node_key within
-- the same snapshot. Every edge is traceable (source) and honest about whether it
-- is a measured fact or a model-derived prediction (confidence).
CREATE TABLE kg_edges (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id  NUMBER        NOT NULL,
  disease_id   VARCHAR2(100) NOT NULL,
  src_key      VARCHAR2(200) NOT NULL,   -- from-node node_key
  dst_key      VARCHAR2(200) NOT NULL,   -- to-node node_key
  rel_type     VARCHAR2(40)  NOT NULL,   -- interacts_with | paralog_of | associated_with | dysregulated_in
                                         -- | targeted_by | tested_in | for | in_pathway | peaks_in
                                         -- | has_variant | mentioned_in | studied_in
  weight       NUMBER,                   -- edge strength (score / freq / STRING confidence…)
  confidence   VARCHAR2(20),             -- fact (measured) | prediction (model-derived)
  source       VARCHAR2(200),            -- provenance (STRING v12, Open Targets, cBioPortal…)
  props_json   CLOB,                     -- structured payload (per-edge detail)
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_kge_json CHECK (props_json IS JSON),
  CONSTRAINT fk_kge_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES target_ranking_snapshots (id) ON DELETE CASCADE
);
CREATE INDEX idx_kge_snapshot ON kg_edges (snapshot_id);
CREATE INDEX idx_kge_src      ON kg_edges (snapshot_id, src_key);
CREATE INDEX idx_kge_dst      ON kg_edges (snapshot_id, dst_key);
CREATE INDEX idx_kge_rel      ON kg_edges (snapshot_id, rel_type);


-- ── GRANTS to the runtime role ──────────────────────────────────────────────
-- Projected graph: full read/write (the projector rebuilds it; the app reads it).
GRANT SELECT, INSERT, UPDATE, DELETE ON kg_nodes TO DISEASE2TARGET_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON kg_edges TO DISEASE2TARGET_RW;
