-- ============================================================================
-- Disease2Target — network-centrality tables (WINNER runs, graph contexts, scores)
-- Run as DISEASE2TARGET_OWNER:  node --env-file=.env docs/oracle/run_sql.cjs docs/sql/network_tables.sql
-- Compatible with Oracle 19c+.
--
-- Why four tables and not a column on RANKING_SCORES: a WINNER score is a property of
--   gene + graph universe + run parameters,
-- never of the gene alone. The same gene scores differently on the Alzheimer top-6,000
-- graph, an expanded top-8,000 graph, and the global 19k STRING interactome, and those
-- values must never be compared. PRIMARY KEY (run_id, gene_symbol) makes mixing impossible.
--
--   network_graph            the graph universe (STRING version, threshold, node/edge counts)
--   network_run              one algorithm execution on one graph (parameters, disease context)
--   network_score            one row per gene per run, with an explicit STATUS (never zero-for-missing)
--   gene_identifier_mapping  Open Targets symbol -> STRING preferred name, with how it was resolved
-- plus RANKING_SCORES.candidate_source so appended genes (e.g. Agora) keep their provenance.
-- ============================================================================


-- ── 1. NETWORK_GRAPH ────────────────────────────────────────────────────────
CREATE TABLE network_graph (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  graph_key          VARCHAR2(120) NOT NULL,      -- e.g. S103_TOP6000_STRING12.0_400 or STRING_GLOBAL_12.0_400
  graph_type         VARCHAR2(30)  NOT NULL,      -- DISEASE_CANDIDATES | GLOBAL | EXPANDED | CUSTOM
  source             VARCHAR2(40)  NOT NULL,      -- STRING
  source_version     VARCHAR2(20)  NOT NULL,      -- 12.0
  species            VARCHAR2(10)  NOT NULL,      -- 9606
  min_score          NUMBER        NOT NULL,      -- STRING combined-score threshold (400)
  construction       VARCHAR2(1000),              -- how nodes/edges were formed (isoform collapse, self-edges)
  snapshot_id        NUMBER,                      -- the candidate snapshot this graph was induced from (NULL = global)
  candidate_rule     VARCHAR2(400),               -- e.g. "stored rank_position <= 6000"
  node_count         NUMBER,
  edge_count         NUMBER,
  isolated_count     NUMBER,
  n_input_symbols    NUMBER,                      -- symbols asked for (before mapping)
  mapping_json       CLOB,                        -- {EXACT:n, ALIAS:n, ABSENT_FROM_STRING:n, ...}
  files_json         CLOB,                        -- SHA-256 of the STRING flat files used
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_ng_key UNIQUE (graph_key),
  CONSTRAINT chk_ng_map_json CHECK (mapping_json IS JSON),
  CONSTRAINT chk_ng_files_json CHECK (files_json IS JSON),
  CONSTRAINT fk_ng_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES target_ranking_snapshots (id) ON DELETE SET NULL
);


-- ── 2. NETWORK_RUN ──────────────────────────────────────────────────────────
CREATE TABLE network_run (
  id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  graph_id                NUMBER        NOT NULL,
  algorithm               VARCHAR2(40)  NOT NULL,   -- WINNER | RWR
  implementation          VARCHAR2(120) NOT NULL,   -- winner-net (aimed-lab/WINNER python) | d2t sparse port
  implementation_version  VARCHAR2(40),
  sigma                   NUMBER,                   -- damping (0.85)
  iterations              NUMBER,                   -- 100
  initialisation          VARCHAR2(200),            -- wdeg^2/deg (RunWinner.m) | seed vector (RWR)
  normalisation           VARCHAR2(200),            -- raw/max, midrank percentile within run
  disease_id              VARCHAR2(100),            -- NULL for the global run
  snapshot_id             NUMBER,                   -- NULL for the global run
  candidate_rule          VARCHAR2(400),
  context_label           VARCHAR2(200) NOT NULL,   -- shown in the UI: "Alzheimer disease / Open Targets top 6,000"
  is_primary              NUMBER(1) DEFAULT 0 NOT NULL,  -- 1 = the run the board's Network criterion reads for this snapshot
  params_json             CLOB,                     -- anything else (seed genes, restart prob, package version string)
  created_by              VARCHAR2(200),
  created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_nr_params_json CHECK (params_json IS JSON),
  CONSTRAINT fk_nr_graph FOREIGN KEY (graph_id) REFERENCES network_graph (id) ON DELETE CASCADE,
  CONSTRAINT fk_nr_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES target_ranking_snapshots (id) ON DELETE SET NULL
);
CREATE INDEX idx_nr_snapshot ON network_run (snapshot_id, is_primary);


-- ── 3. NETWORK_SCORE ────────────────────────────────────────────────────────
-- One row per gene per run. STATUS says why a score is or is not there:
--   PRESENT               scored (raw may legitimately be 0 for an isolated node)
--   ABSENT_FROM_GRAPH     in the candidate set but not resolvable to STRING at this version
--   NOT_IN_CANDIDATE_SET  in the snapshot but outside the graph's candidate rule (e.g. Agora-only rows)
--   NOT_COMPUTED | ERROR
CREATE TABLE network_score (
  run_id          NUMBER        NOT NULL,
  gene_symbol     VARCHAR2(64)  NOT NULL,
  string_name     VARCHAR2(64),             -- STRING preferred name the symbol resolved to
  raw_score       NUMBER,
  norm_score      NUMBER,                   -- raw / max(raw) within the run
  percentile      NUMBER,                   -- midrank percentile within the run, 0..100 (the ranking feature)
  rank_position   NUMBER,                   -- 1 = highest score in the run
  degree          NUMBER,                   -- edges at threshold within THIS graph
  weighted_degree NUMBER,
  p_value         NUMBER,                   -- degree-preserving null (RunWinner_withPValue) — NULL until computed
  fdr             NUMBER,
  status          VARCHAR2(30)  NOT NULL,
  CONSTRAINT pk_ns PRIMARY KEY (run_id, gene_symbol),
  CONSTRAINT chk_ns_status CHECK (status IN ('PRESENT','ABSENT_FROM_GRAPH','NOT_IN_CANDIDATE_SET','NOT_COMPUTED','ERROR')),
  CONSTRAINT fk_ns_run FOREIGN KEY (run_id) REFERENCES network_run (id) ON DELETE CASCADE
);
CREATE INDEX idx_ns_gene ON network_score (gene_symbol);


-- ── 4. GENE_IDENTIFIER_MAPPING ──────────────────────────────────────────────
-- Open Targets symbol -> STRING preferred name. Keeps "renamed" apart from "absent".
--   EXACT | ALIAS | OVERRIDE | AMBIGUOUS | COLLISION | ABSENT_FROM_STRING
CREATE TABLE gene_identifier_mapping (
  id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gene_symbol          VARCHAR2(64)  NOT NULL,   -- as used in RANKING_SCORES / EVIDENCE (Open Targets approvedSymbol)
  source               VARCHAR2(40)  DEFAULT 'OPEN_TARGETS' NOT NULL,
  target_source        VARCHAR2(40)  NOT NULL,   -- STRING
  target_version       VARCHAR2(20)  NOT NULL,   -- 12.0
  resolved_identifier  VARCHAR2(64),             -- STRING preferred name (NULL when unresolved)
  mapping_status       VARCHAR2(30)  NOT NULL,
  mapping_method       VARCHAR2(80),             -- preferred_name | Ensembl_HGNC_prev_symbol | symbol_overrides.tsv | ...
  note                 VARCHAR2(400),
  updated_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_gim UNIQUE (gene_symbol, source, target_source, target_version),
  CONSTRAINT chk_gim_status CHECK (mapping_status IN ('EXACT','ALIAS','OVERRIDE','AMBIGUOUS','COLLISION','ABSENT_FROM_STRING'))
);


-- ── 5. RANKING_SCORES.candidate_source ──────────────────────────────────────
-- Who put the gene in the snapshot. Harvest rows are OPEN_TARGETS; appended rows carry
-- their own label (AGORA, MANUAL, ...). Never relabel an appended gene as an OT candidate.
ALTER TABLE ranking_scores ADD (candidate_source VARCHAR2(40) DEFAULT 'OPEN_TARGETS' NOT NULL);


-- ── GRANTS to the runtime role ──────────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON network_graph           TO DISEASE2TARGET_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_run             TO DISEASE2TARGET_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_score           TO DISEASE2TARGET_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON gene_identifier_mapping TO DISEASE2TARGET_RW;
