-- ============================================================================
-- Oracle DDL — content-centric storage for Disease2Target
-- Run while connected as DISEASE2TARGET_OWNER (e.g. in SQL Developer / SQLcl /
-- Oracle SQL web).  Mirrors the Supabase snapshots table.
-- Compatible with Oracle 19c+ (uses CLOB IS JSON; on 21c+ you may swap CLOB→JSON).
-- ============================================================================

CREATE TABLE target_ranking_snapshots (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disease_id    VARCHAR2(100)  NOT NULL,
  disease_name  VARCHAR2(400)  NOT NULL,
  version       NUMBER         NOT NULL,
  created_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  created_by    VARCHAR2(200),
  label         VARCHAR2(400),
  gene_count    NUMBER,
  weights       CLOB,
  provenance    CLOB,
  targets       CLOB,
  CONSTRAINT chk_trs_weights    CHECK (weights    IS JSON),
  CONSTRAINT chk_trs_provenance CHECK (provenance IS JSON),
  CONSTRAINT chk_trs_targets    CHECK (targets    IS JSON)
);

CREATE INDEX idx_trs_disease ON target_ranking_snapshots (disease_id, version);
CREATE INDEX idx_trs_created ON target_ranking_snapshots (created_at);

-- Quick check that you have the privileges/quota:
--   INSERT INTO target_ranking_snapshots (disease_id, disease_name, version, targets)
--   VALUES ('TEST', 'Test disease', 1, '[]');
--   COMMIT;
--   SELECT id, disease_name, version, created_at FROM target_ranking_snapshots;
--   DELETE FROM target_ranking_snapshots WHERE disease_id = 'TEST'; COMMIT;
