-- ============================================================================
-- Disease2Target — Oracle content tables (phase 1)
-- Run as DISEASE2TARGET_OWNER, after target_ranking_snapshots already exists.
-- Compatible with Oracle 19c+.
--
-- Three tables:
--   ranking_scores  — flattened per-gene scores (queryable, for benchmarking)
--   evidence        — per-gene evidence items with full provenance (traceability)
--   audit_log       — append-only event trail (who / what / when)
-- ============================================================================


-- ── 1. RANKING_SCORES ───────────────────────────────────────────────────────
-- One row per gene per snapshot. Lets you query/benchmark in SQL, e.g.
--   "what rank did KRAS get in pancreatic cancer across versions?"
CREATE TABLE ranking_scores (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id       NUMBER        NOT NULL,   -- which ranking run this belongs to
  disease_id        VARCHAR2(100) NOT NULL,
  disease_name      VARCHAR2(400),
  gene_symbol       VARCHAR2(64)  NOT NULL,
  gene_name         VARCHAR2(400),
  rank_position     NUMBER,                   -- 1 = top of the ranked list
  overall_score     NUMBER,                   -- Open Targets association score
  get_score         NUMBER,                   -- composite GET = G*0.5 + E*0.25 + T*0.25
  genetic_score     NUMBER,
  expression_score  NUMBER,
  target_score      NUMBER,
  literature_score  NUMBER,
  tau_tissue        NUMBER,                   -- Protein Atlas tissue specificity
  tau_single_cell   NUMBER,
  bimodality_max    NUMBER,
  bimodality_tissue VARCHAR2(200),
  pubtator_score    NUMBER,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_rs_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES target_ranking_snapshots (id) ON DELETE CASCADE
);
CREATE INDEX idx_rs_snapshot ON ranking_scores (snapshot_id);
CREATE INDEX idx_rs_gene     ON ranking_scores (disease_id, gene_symbol);


-- ── 2. EVIDENCE ─────────────────────────────────────────────────────────────
-- One row per evidence item. Every value is traceable: where it came from,
-- when, by what, and whether it's been audited.
CREATE TABLE evidence (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id    NUMBER,                       -- optional link to the ranking run
  disease_id     VARCHAR2(100) NOT NULL,
  gene_symbol    VARCHAR2(64)  NOT NULL,
  evidence_type  VARCHAR2(60)  NOT NULL,       -- druggability | clinical | literature | genetic | expression | tissue | mutation
  source         VARCHAR2(100) NOT NULL,       -- ChEMBL | Open Targets | PubMed | Europe PMC | ClinicalTrials.gov | Protein Atlas | PubTator
  source_url     VARCHAR2(1000),               -- link to the source record
  value_text     VARCHAR2(4000),               -- short human-readable value
  value_json     CLOB,                         -- structured payload (optional)
  retrieved_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  generated_by   VARCHAR2(200),                -- agent / app / user that produced it
  audit_status   VARCHAR2(40) DEFAULT 'not_audited' NOT NULL,  -- not_audited | ai_verified | human_verified
  CONSTRAINT chk_ev_json CHECK (value_json IS JSON),
  CONSTRAINT fk_ev_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES target_ranking_snapshots (id) ON DELETE SET NULL
);
CREATE INDEX idx_ev_gene   ON evidence (disease_id, gene_symbol);
CREATE INDEX idx_ev_type   ON evidence (evidence_type);
CREATE INDEX idx_ev_source ON evidence (source);


-- ── 3. AUDIT_LOG (append-only) ──────────────────────────────────────────────
-- Immutable event trail. The app/role gets SELECT + INSERT only (no UPDATE/DELETE),
-- so history can never be rewritten.
CREATE TABLE audit_log (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  actor       VARCHAR2(200),                   -- user email / agent name
  action      VARCHAR2(100) NOT NULL,          -- snapshot_saved | snapshot_deleted | evidence_fetched | ranking_loaded
  entity      VARCHAR2(100),                   -- table/entity affected
  entity_id   VARCHAR2(100),
  disease_id  VARCHAR2(100),
  details     CLOB,
  CONSTRAINT chk_audit_json CHECK (details IS JSON)
);
CREATE INDEX idx_audit_time   ON audit_log (event_time);
CREATE INDEX idx_audit_action ON audit_log (action);


-- ── GRANTS to the runtime role ──────────────────────────────────────────────
-- Content tables: full read/write.
GRANT SELECT, INSERT, UPDATE, DELETE ON ranking_scores TO DISEASE2TARGET_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON evidence       TO DISEASE2TARGET_RW;

-- Audit table: APPEND-ONLY (no UPDATE/DELETE) so the trail is tamper-proof.
GRANT SELECT, INSERT                 ON audit_log       TO DISEASE2TARGET_RW;
